spring:
  profiles:
    include:
      - oauth2
      - jwt
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  datasource: # DB 커넥션 설정
    url: jdbc:postgresql://localhost:5432/wordsketch?serverTimezone=UTC&characterEncoding=UTF-8
    username: pantsadmin
    password: ddongpants
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update # 어플리케이션 실행 시, DB 테이블 자동생성 방식
      # create : 애플리케이션 실행 시 테이블을 모두 제거하고 다시 생성 (drop & create)
      # create-drop : 애플리케이션 실행 시 테이블을 모두 제거하고 다시 생성하며, 애플리케이션 종료 시점에 테이블을 모두 제거 (drop & create & drop)
      # update : 애플리케이션 실행 시 변경점만 반영
      # validate : 현재 테이블 정보가 entity에 정의된 내용과 동일한지 체크 후, 다를 경우 경고를 출력하며 애플리케이션을 실행하지 않음
      # none : 자동생성을 사용하지 않음
    show-sql: true
logging: # 서버 로그 설정
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace # 쿼리의 ?에 어떤 값이 들어가는지 TRACE Log에 값을 보여주는 설정
      springframework:
        security: TRACE
